config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#home'

  get 'pages/home'

  get 'pages/about'

  get 'check/index' 
    
    get 'check' => 'check#index' 

  get 'check/theme_page'

  get 'check/article_page'
  
  get 'check/update_database' 
    
    get 'check/update_article_database' 
    
    get 'check/update_themepage_database' 
    
  get 'visibility/sistrix_page'

  get 'visibility/index'
    
    get 'visibility' => 'visibility#index' 
  
 get 'visibility/update_database'  => 'visibility#index'    
    
  get 'visibility/searchmetrics_page'

end

app/controllers/visibility_controller.rb
class VisibilityController < ApplicationController
  	helper_method :sort_column_visibility, :sort_direction
  def index

 	end

 	def searchmetrics_page
     @searchmetrics_items_all = SearchmetricsIndex.all  
 	end

  def sistrix_page
      #get_sistrix_visibility_per_channel_history(get_sistrix_api_key)
      @sistrix_items = SistrixVisibilityIndex.order(sort_column_visibility + " " + sort_direction).paginate(:per_page => 50, :page => params[:page])
      @sistrix_items_all = SistrixVisibilityIndex.all   
  end

    def update_database
        get_sistrix_visibility_per_channel(get_sistrix_api_key)
        render 'index'
    end
    
    
  private 
  
	def get_sistrix_keyword_count(domain, api_key)
		  url = "http://api.sistrix.net/domain.kwcount.seo?api_key=#{api_key}&path=#{domain}"
		  doc = Nokogiri::XML(open(url))
		  kwcount = doc.xpath("//response/answer/kwcount.seo/@value")
      return kwcount
	end


	def get_sistrix_visibility_index(domain, api_key)
		  url = "http://api.sistrix.net/domain.sichtbarkeitsindex?api_key=#{api_key}&path=#{domain}"
		  doc = Nokogiri::XML(open(url))
		  svi = doc.xpath("//response/answer/sichtbarkeitsindex/@value")
        date = doc.xpath("//response/answer/sichtbarkeitsindex/@date").text
        return svi,date
	end
    
    def get_sistrix_visibility_index_per_date(domain, api_key, date)
		  url = "http://api.sistrix.net/domain.sichtbarkeitsindex?api_key=#{api_key}&path=#{domain}?history=true?date=#{date}"
		  doc = Nokogiri::XML(open(url))
		  svi = doc.xpath("//response/answer/sichtbarkeitsindex/@value")
      return svi
	end    
    
    def get_channels
         channels = ["http://www.welt.de/", "http://www.welt.de/themen/", "http://www.welt.de/debatte", "http://www.welt.de/fernsehen/", "http://www.welt.de/geschichte/", "http://www.welt.de/gesundheit/", "http://www.welt.de/icon/", "http://www.welt.de/kultur/", "http://www.welt.de/motor/", "http://www.welt.de/politik/", "http://www.welt.de/reise/", "http://www.welt.de/satire/", "http://www.welt.de/sport", "http://www.welt.de/vermischtes", "http://www.welt.de/wirtschaft/", "http://www.welt.de/wissenschaft/"] 
        return channels
    end
    
    def get_dates
        dates = ["2015-06-01", "2015-05-25", "2015-05-18", "2015-05-11", "2015-05-04", "2015-04-27", "2015-04-20", "2015-04-13", "2015-04-06T00:00:00+02:00", "2015-03-30T00:00:00+02:00", "2015-03-23T00:00:00+01:00", "2015-03-16", "2015-03-09", "2015-03-02", "2015-02-23", "2015-02-16", "2015-02-09", "2015-02-02", "2015-01-26", "2015-01-19", "2015-01-12", "2015-01-05"]
        return dates
    end
    
    
    def get_sistrix_visibility_per_channel(api_key)
         channels = get_channels
        channels.each do |c|
            sistrix_index, date = get_sistrix_visibility_index(c, api_key)
            channel = get_channel(c)
            kw = date
        begin
            store_sistrix_visibility_indices(c, channel, kw, sistrix_index)
        end
      end
  end

    def get_sistrix_visibility_per_channel_history(api_key)
        #for storing historical data from sistrix api
        channels = get_channels
        date = get_dates
        channels.each do |c|
            date.each do |date|
                sistrix_index = get_sistrix_visibility_index_per_date(c, api_key, date)
                channel = get_channel(c)
                kw = date
                begin
                  store_sistrix_visibility_indices(c, channel, kw, sistrix_index)
                end
            end
        end
  end
    
  def get_channel(url)
      return url
      #to do implement channel
  end

  def get_calendar_week
      return Time.now.strftime("%W").to_i
  end

  def store_sistrix_visibility_indices(url, channel, kw, sistrix_index)
      if (SistrixVisibilityIndex.find_by_url(url) == nil)
          SistrixVisibilityIndex.create(:url => url, :channel => channel, :kw => kw, :sistrix_index => sistrix_index)
          
    elsif (SistrixVisibilityIndex.find_by_url_and_kw(url, kw) == nil)
	  		 SistrixVisibilityIndex.create(:url => url, :channel => channel, :kw => kw, :sistrix_index => sistrix_index)
    else 
          SistrixVisibilityIndex.find_by_url(url).delete 
          SistrixVisibilityIndex.create(:url => url, :channel => channel, :kw => kw, :sistrix_index => sistrix_index)
        end
  end

  def get_sistrix_api_key
      return "2QJTp3HNTkuqBZhcMPrayBQkdFpFQh87"
  end

  def sort_column_visibility
      SistrixVisibilityIndex.column_names.include?(params[:sort]) ? params[:sort] : "sistrix_index"
  end
    
  def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

end

app/helpers/visibility_helper.rb
module VisibilityHelper

	def sortable_visibility(column, title = nil)
		  title ||= column.titleize
		  css_class = column == sort_column_visibility ? "current #{sort_direction}" : nil
		  direction = column == sort_column_visibility && sort_direction == "asc" ? "desc" : "asc"
		  link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
	end

end

app/views/visibility/index.html.erb
<% provide(:title, 'SEO Visibility') %>
<% @body_id = "login-page" %>

<div class="row">
     <div class="col-lg-12">
       <div class="jumbotron">
         <h1>WeltN24 Sichtbarkeit</h1>
         <p>
            <%= link_to "Sistrix", visibility_sistrix_page_path, :class => "btn btn-success" %>
            <%= link_to "Searchmetrics", visibility_searchmetrics_page_path, :class => "btn btn-success" %>
         </p>
       </div>
     </div>       
		
</div>

app/views/visibility/searchmetrics_page.html.erb
<h1>Visibility#searchmetrics_page</h1>
<p>Find me in app/views/visibility/searchmetrics_page.html.erb</p>

app/views/visibility/sistrix_page.html.erb
<% provide(:title, 'Sistrix Sichtbarkeitsindex') %>
<% @body_id = "sistrix-page" %>

  <div class="row">
     <div class="col-lg-12">
           <h1 class="page-header">Sistrix Sichtbarkeitsindex</h1>
      </div>   
         </div>
       <div class="row">
           <div class="col-lg-12">
      <div class="panel panel-default">
      <div class="panel-heading" name="top-ten-results" id="top-ten-results">
		</div>
      	<div class="panel-body">
            <ul class="nav nav-tabs">
              <li role="presentation" class="active"><a data-toggle="tab" href="#welt">welt.de</a></li>
              <li role="presentation"><a data-toggle="tab" href="#focus">focus.de</a></li>
            </ul>
            <div class="tab-content">
                <div id="welt" class="tab-pane fade in active">
                      <div class="table-responsive">
                         <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                            <tr>
                                            <th><%= sortable_visibility "channel", "Channel" %></th>
                                            <th><%= sortable_visibility "url", "URL" %></th>
                                            <th><%= sortable_visibility "kw", "KW" %></th>
                                            <th><%= sortable_visibility "sistrix_index", "SI" %></th>
                                            </tr>
                                    </thead>
                                      <tbody>
                                          <% @sistrix_items.each_with_index do |s, i|  %>
                                            <tr>
                                              <td><%= s.channel %></td>
                                              <td><a target=_blank href="<%= s.url %>"><%= s.url %></a> </td>
                                              <td><%= s.kw %></td>
                                              <td><%= s.sistrix_index %></td>
                                            </tr>
                                            <% end %>
                                        </tbody>
                                </table>
                        <%= will_paginate @sistrix_items, renderer: BootstrapPagination::Rails%>
			         </div>
                    </div>
            
            <div id="focus" class="tab-pane fade">
                    
                </div>
                </div><!-- tab content -->
          </div>
          <!-- panel body -->
	</div>
	</div><!-- span12 -->
    </div>  <!-- row -->