config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#home'

  get 'pages/home'

  get 'pages/about'

  get 'check/index' 
    
    get 'check' => 'check#index' 

  get 'check/theme_page'

  get 'check/article_page'
  
  get 'check/update_database' 
    
    get 'check/update_article_database' 
    
    get 'check/update_themepage_database' 
    
  get 'visibility/sistrix_page'

  get 'visibility/index'
    
    get 'visibility' => 'visibility#index' 
  
 get 'visibility/update_database'  => 'visibility#index'    
    
  get 'visibility/searchmetrics_page'

end

app/views/layouts/_footer.html.erb
<a href="#" class="back-to-top" style="display: inline;">
<i class="fa fa-arrow-circle-up"></i>
</a>
<div class="footer">
    <div class="row">
        <div class="col-lg-12">
    <p class="muted credit">© WeltN24 2015</p>
        </div>
        </div>
</div>
    

  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <script src="//www.google.com/jsapi"></script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<!--

Template: SB Admin V2 
https://github.com/ironsummitmedia/startbootstrap/ 
Copyright 2013 Iron Summit Media Strategies

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 .
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/ -->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">WeltN24 SEO Dashboard</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                        <% if user_signed_in? %>
                    <%= link_to(raw("<i class='fa fa-user fa-fw'></i><b class= 'caret'></b>"), "#", :class => "dropdown-toggle", :data => {:toggle=>"dropdown"}) %>
                                        <ul class="dropdown-menu dropdown-user">
                                    
                                            <li><% if user_signed_in? %>
                                                 <%= link_to edit_user_registration_path do %><i class="fa fa-gear fa-fw"></i> Settings<% end %>
                                                <% else %><%end%>
                                            </li>
                                            <li class="divider"></li>
                                            <li><% if user_signed_in? %>
                                                 <%= link_to destroy_user_session_path, method: :delete do %><i class="fa fa-sign-out fa-fw"></i> Log out<% end %>
                                                <% else %><%end%>
                                            </li>
                                        </ul>
                        <% else %>  <% end %>
                                        <!-- /.dropdown-user -->
                    </li>
                    <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default navbar-static-side" role="navigation">
                <div class="sidebar-collapse" style="height: 0px;">
                    <ul class="nav" id="side-menu">
                        <li class="">
                            <a href=""><i class="fa fa-bar-chart-o fa-fw"></i> Quality<span class="fa arrow"></span></a>
                            
                            <ul class="nav nav-second-level collapse" style="height: 0px;">
                                <li>
                                    <%= link_to "Themepage Check", check_theme_page_path %>
                                </li>
                                <li>
                                    <%= link_to "Articlepage Checks", check_article_page_path %>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li class="">
                            <a href=""><i class="fa fa-bar-chart-o fa-fw"></i> Visibility<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse" style="height: 0px;">
                                <li>
                                    <%= link_to "Sistrix Visibility", visibility_sistrix_page_path %>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                    <!-- /#side-menu -->
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript">
    </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title><%= yield(:title) %> | WeltN24 SEO Dashboard</title>
  <link rel="stylesheet" id="font-awesome-css" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" type="text/css" media="screen">
     <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <!-- Page-Level Plugin CSS - Dashboard -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
</head>

<body id="<%= @body_id %>">
<% if user_signed_in? %>	
<%= render 'layouts/header' %>

   <div id="page-wrapper">
     <div class="row">
		<div id="alert">
		 	   <% if notice %>
		 	     <p class="alert alert-notice"><%= notice %></p>
		 	   <% end %>
		 	   <% if alert %>
		 	     <p class="alert alert-error"><%= alert %></p>
		 	   <% end %>
		</div>
  </div>
	   	<%= yield %>
      </div>
      <!-- /#page-wrapper -->
		<%= render 'layouts/footer' %>
   <!-- /#wrapper -->
   
   <% else %>	
   <div id="page-wrapper">
		<div id="alert">
		 	   <% if notice %>
		 	     <p class="alert alert-notice"><%= notice %></p>
		 	   <% end %>
		 	   <% if alert %>
		 	     <p class="alert alert-error"><%= alert %></p>
		 	   <% end %>
		</div>
	   	<%= yield %>
  </div>
   <!-- /#page-wrapper -->
   <%= render 'layouts/footer' %>
   
  
<% end %>
 

  
</body>
</html>